#Feature: Create lead functionality of Testleaf application. 
#Scenario Outline: Create lead test 
#
#	Given launch the application for create lead
#	And Type the username as <uname>
#	And Type the password for CL as <password>
#	And Go to click the loginbtn for CL
#	And click CRMSFA link
#	And click leads button
#	And click Createlead button
#	And enter the company name
#	And Enter first name
#	And Enter last name
#	And click Create lead button
#	
#	Examples:
#	|uname||password|
#	|DemoSalesManager||crmsfa|